# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.4.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: angus@oieltd.com
author_name: Angus
has_binder: false
has_settings: false
kind: frontend
labextension_name: myextension
project_short_description: A JupyterLab extension.
python_name: myextension
repository: ''
test: false

